- platform: template
  name: TV
  value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
  turn_on:
    service: remote.turn_on
    data:
      entity_id: remote.harmony_hub
      activity: '23707281'
  turn_off:
    service: remote.turn_on
    data:
      entity_id: remote.harmony_hub
      activity: '-1'